# ===============================
# Application
# ===============================
quarkus.application.name=clinica-api
quarkus.http.port=${PORT:8080}
quarkus.live-reload.enabled=true
quarkus.log.level=${LOG_LEVEL:DEBUG}

# ===============================
# Security/JWT
# ===============================
# Localização das chaves PEM (arquivo no classpath para dev, override via env var em produção)
smallrye.jwt.sign.key.location=${JWT_PRIVATE_KEY_LOCATION:META-INF/microprofile-jwt/privateKey.pem}
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_LOCATION:META-INF/microprofile-jwt/publicKey.pem}

mp.jwt.verify.issuer=${JWT_ISSUER:clinica-api}
quarkus.smallrye-jwt.enabled=true
jwt.expiration.minutes=${TEMPO_EXPIRACAO_APP:15}
quarkus.http.auth.proactive=false


# ===============================
# Datasource REACTIVE (runtime)
# ===============================
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://localhost:5432/${POSTGRES_DB}
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}
quarkus.datasource.reactive.max-size=20
quarkus.datasource.reactive.idle-timeout=PT5M

# ===============================
# Datasource JDBC (APENAS Flyway)
# ===============================
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}

# ===============================
# Hibernate Reactive
# ===============================
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=${HIBERNATE_LOG_SQL}
quarkus.log.category."org.hibernate".level=${HIBERNATE_LOG_LEVEL}

# ===============================
# Flyway
# ===============================
quarkus.flyway.active=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=clinica
quarkus.flyway.default-schema=clinica
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.locations=classpath:db/migration

# ===============================
# OpenAPI
# ===============================
quarkus.smallrye-openapi.path=/swagger

# ===============================
# Redis
# ===============================
quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.password=${REDIS_PASSWORD}
refresh.token.ttl=${REDIS_TEMPO_REFRESH_TOKEN}
quarkus.redis.timeout=${REDIS_TIMEOUT}

# ===============================
# Test
# ===============================
#%test.quarkus.http.port=0
#%test.quarkus.http.ssl-port=0

# ===============================
# Mailer
# ===============================
quarkus.mailer.from=${MAILER_FROM}
quarkus.mailer.host=${MAILER_HOST}
quarkus.mailer.port=${MAILER_PORT}
quarkus.mailer.start-tls=${MAILER_STARTTLS}
quarkus.mailer.username=${MAILER_USERNAME}
quarkus.mailer.password=${MAILER_PASSWORD}
quarkus.mailer.auth-methods=${MAILER_AUTH_METHODS}
quarkus.mailer.mock=false