ALTER TABLE clinica.paciente
ADD COLUMN logradouro VARCHAR(255),
ADD COLUMN numero VARCHAR(50),
ADD COLUMN bairro VARCHAR(255),
ADD COLUMN cep VARCHAR(20),
ADD COLUMN complemento VARCHAR(255),
ADD COLUMN cidade VARCHAR(255),
ADD COLUMN estado VARCHAR(50),
ADD COLUMN pais VARCHAR(50);
